version: "3.7"
services:
  laravel.test:
    build:
        context: ./vendor/laravel/sail/runtimes/8.0
        dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: sail-8.0/app
    port:
        -'${APP_PORT:-80}:80'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
   myproject_web:
    image: pablofmorales/apache-php7
    container_name: myproject_web
    ports:
        - "80:80"
    volumes:
        - ./:/var/www/html
        - ./apache.conf:/etc/apache2/sites-enabled/myproject-web.conf
        - ./var/log:/var/log/apache2
    links:
        - myproject_redis
        - myproject_mongodb
    myproject_mongodb:
    container_name: myproject_mongodb
    image: mongo:latest
    ports:
        - "27017:27017"
networks:
  landing:
    driver: bridge